disabled_rules:
- identifier_name
- line_length
- force_cast
- force_try
- cyclomatic_complexity
- type_body_length
- file_length
- function_body_length
- large_tuple
- type_name

opt_in_rules:
- empty_count
- empty_string
- first_where
- modifier_order
- toggle_bool
- collection_alignment
