platform :ios, '13.0'

target 'MusicXML-Swift' do
  use_frameworks!

  target 'MusicXML-SwiftTests' do
    inherit! :search_paths
  end

  target 'MusicXML-SwiftTests-Snapshots' do
    inherit! :search_paths
    pod 'iOSSnapshotTestCase'
  end

end
